# Generated by Django 4.2.1 on 2023-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_gather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_name',
            field=models.CharField(default='Event Name', max_length=50),
        ),
    ]
