# Generated by Django 4.2.1 on 2023-11-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_gather_app', '0002_events_event_description_events_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_organiser',
            field=models.TextField(null=True),
        ),
    ]
